INCS += -Iarch/$(CPU_DIR)/bsp 
INCS += -Iarch/$(CPU_DIR)/cmsis/inc 
INCS += -Iarch/$(CPU_DIR)/cmsis/inc/st

OBJS += arch/$(CPU_DIR)/cmsis/src/st/system_stm32f7xx.o

OBJS += arch/$(CPU_DIR)/bsp/sys.o
OBJS += arch/$(CPU_DIR)/bsp/gpio.o
OBJS += arch/$(CPU_DIR)/bsp/usart.o
