INCS += -Iarch/$(CPU_DIR)/bsp 
INCS += -Iarch/$(CPU_DIR)/hal_lib/inc 
INCS += -Iarch/$(CPU_DIR)/cmsis/inc 
INCS += -Iarch/$(CPU_DIR)/cmsis/inc/st

OBJS += arch/$(CPU_DIR)/cmsis/src/st/system_stm32f7xx.o
OBJS += arch/$(CPU_DIR)/hal_lib/src/stm32f7xx_hal.o
OBJS += arch/$(CPU_DIR)/hal_lib/src/stm32f7xx_hal_rcc.o
OBJS += arch/$(CPU_DIR)/hal_lib/src/stm32f7xx_hal_rcc_ex.o
OBJS += arch/$(CPU_DIR)/hal_lib/src/stm32f7xx_hal_pwr.o
OBJS += arch/$(CPU_DIR)/hal_lib/src/stm32f7xx_hal_pwr_ex.o
OBJS += arch/$(CPU_DIR)/hal_lib/src/stm32f7xx_hal_gpio.o
OBJS += arch/$(CPU_DIR)/hal_lib/src/stm32f7xx_hal_cortex.o

OBJS += arch/$(CPU_DIR)/bsp/gpio.o
OBJS += arch/$(CPU_DIR)/bsp/usart.o
